### ISSUE TITLE
RCharts Installation issues!

### ISSUE THREAD

**Issue by bshoemaker12** [ramnathv/rCharts#155]
I have tried a variety of avenues to install Rcharts with no success. Here's what I've seen:

> require(devtools)
> install_github('rCharts', 'ramnathv')
> Installing github repo(s) rCharts/master from ramnathv
> Installing rCharts.zip from https://github.com/ramnathv/rCharts/archive/master.zip
> Error in function (type, msg, asError = TRUE)  : 
>   Peer certificate cannot be authenticated with given CA certificates

After this problem, I tried to download the tarball from the rcharts site, and do a manual install, getting the following message: 

> require(devtools)
> install.packages("~/ramnathv-rCharts-4875ed1.tar.gz",repos=NULL,type = "source")
> Warning in install.packages :
>   package ‘~/ramnathv-rCharts-4875ed1.tar.gz’ is not available (for R version 2.15.3)
> Installing package(s) into ‘/home/[username]/R/x86_64-pc-linux-gnu-library/2.15’
> (as ‘lib’ is unspecified)
> Warning in untar2(tarfile, files, list, exdir) :
>   skipping pax global extended headers
> ERROR: cannot extract package from ‘/home/[username]/ramnathv-rCharts-4875ed1.tar.gz’
> Warning in install.packages :
>   installation of package ‘/home/[username]/ramnathv-rCharts-4875ed1.tar.gz’ had non-zero exit status

Lastly, I tried to install from the zip file, getting the following error: 

> install.packages("~/ramnathv-rCharts-4875ed1.zip",repos=NULL,type = "source")
> Warning in install.packages :
>   package ‘~/ramnathv-rCharts-4875ed1.zip’ is not available (for R version 2.15.3)
> Installing package(s) into ‘/home/[username]/R/x86_64-pc-linux-gnu-library/2.15’
> (as ‘lib’ is unspecified)
> Error in rawToChar(block[seq_len(ns)]) : 
>   embedded nul in string: 'PK\003\004\n\0\0\0\0\0@v\xcdB\0\0\0\0\0\0\0\0\0\0\0\0\031\0\t\0ramnathv-rCharts-4875ed1/UT\005\0\001\x89>\xbaQPK\003\004\n\0\0\0\b\0@v\xcdB\xb8\x9f\xae\xc2&\0\0\0*\0\0\0#\0\t\0ramnat'
> Warning in install.packages :
>   installation of package ‘/home/[username]/ramnathv-rCharts-4875ed1.zip’ had non-zero exit status

Anybody got any ideas?! I really want to try this package out

**Comment by wt12315** [comment]
I can't install packages(rCharts) for mac Os X 11.1 R 4.0,please help me!
