### ISSUE TITLE
custom tooltips on barcharts

### ISSUE THREAD

**Issue by twjacobs** [ramnathv/rCharts#170]
I'm trying to use the example code posted for issue 152 on custom tooltips (closed), but I cannot get a barchart working using that code. My dataframe looks like:

```
  Grade Count
1    01 40272
2    02 36902
3    03  1288
4    04   992
5    05   517
6     K   334
7    KA  8236
8    KP  6704
```

I want "Grade" to be the categories.

I thought the following code might work, but it does not. By the way, no tooltips in this yet, just trying to get the barchart to show using this method first. I'll add a column with the tooltip next.

``` coffee
h <- Highcharts$new()
h$chart(type = "bar")
h$series(data = toJSONArray2(myDataFrame, json = F), name = "Counts by Grade")
h$xAxis(categores = cData$Grade)
h
```

**Comment by royfrancis** [comment]
In the above example, the tooltip displays only variable 'Tip'. How would I go about displaying two variables for example, 'y-axis-value' and 'Tip' one below the other?

**Comment by reinholdsson** [comment]
@royfrancis you could add it to the formatter, e.g:

    h$tooltip(useHTML = T, formatter = "#! function() { return this.point.Tip + '<br>' + this.point.Grade; } !#")

**Comment by royfrancis** [comment]
Thanks! :+1:

**Comment by royfrancis** [comment]
I am creating dynamic column plots in a shiny app. I find that
these two approaches works overall but tooltips don't work.
```
#manual names=F
h$series(data = toJSONArray2(cData, json = F,names=F), name = "Counts by Grade")
#hPlot wrapper names=F
h <- rCharts::hPlot(x = "Grade", y = "y", data = cData, type = c("bar"))
```

To make tooltips work, I used this:
```
#manual names=T
h$series(data = toJSONArray2(cData, json = F,names=T), name = "Counts by Grade")
```
Now, the tooltips work fine but this creates too many other issues. Multiple plots don't always load, click and drag gets stuck, sorting column from shiny widget doesn't work etc. So it seems like `names=T` makes tooltip to work but messes up a lot of other stuff. I have tried it outside of shiny environment and it seems to be ok.
