### ISSUE TITLE
datatables advanced example 1 request

### ISSUE THREAD

**Issue by pssguy** [ramnathv/rCharts#192]
I would like to do some cell highlighting and could do with an example to get me started in rCharts
Something like the equivalent of this where the string 'America' would be highlighted

``` json
"aoColumnDefs": [
                {
                    "aTargets":[2], // You actual column with the string 'America'
                    "fnCreatedCell": function(nTd, sData, oData, iRow, iCol)
                    {
                        if(sData == 'America')
                        {
                            $(nTd).css('background-color', 'blue'); // You can use hex code as well
                        }

                    },                   
                }
]
```

**Comment by jermsam** [comment]
Hello.
I am new to dataTables.js and men, it's an amazing solution!
How exactly do I highlight a row based on the sData parameter of the  fnCreatedCell?
I thought about this after failing to use  fnCreatedCell and sClass simultaneously. When I try it, even the cell that I try to highlight with  fnCreatedCell is hidden from view. Is there a way I could use both properties simultaneously?

**Comment by timelyportfolio** [comment]
Not an answer but you might want to look into https://github.com/rstudio/DT from @rstudio.  It is an excellent implementation.
