### ISSUE TITLE
Is there a solution for rCharts to open up from a RStudio Server instance in a browser?

### ISSUE THREAD

**Issue by sckott** [ramnathv/rCharts#195]
This doesn't seem to work. I can make a chart e.g. 

``` coffee
library(rCharts)
names(iris) = gsub("\\.", "", names(iris))
rPlot(SepalLength ~ SepalWidth | Species, data = iris, color = 'Species', type = 'point')
```

And a new browser window opens, but nothing is there. Is there some way to change the port or something like that?  

New tabs open fine to make new rcharts form your rnotebook app run locally, which is neat, but would be great if worked from rstudio server for teaching purposes.

**Comment by mobbSF** [comment]
I am also having a problem. When I run  

```
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, type = "multiBarChart")
n1$print("chart3")
```

I don't get any visual output in RStudio. I am using RStudio version 0.98.1103, and just got the most recent version of rCharts a few minutes ago.
