### ISSUE TITLE
Setting chart width and height for nPlot?

### ISSUE THREAD

**Issue by jeffwong** [ramnathv/rCharts#231]
Is there a way to make a larger NVD3 plot? Right now I think it is set for 800 x 400

``` S
nplot = nPlot(ret ~ event_date, data = mem2, type = "lineWithFocusChart")
nplot$xAxis(
  tickFormat=
    "#!function(d) {return d3.time.format('%Y-%m-%d')(new Date( d * 24 * 60 * 60 * 1000));}!#"
)
nplot$x2Axis(
  tickFormat=
    "#!function(d) {return d3.time.format('%b %Y')(new Date( d * 24 * 60 * 60 * 1000 ));}!#"
)
nplot$set(lineWidth = 1)
nplot
```

**Comment by jsramos** [comment]
Any feedback on this? Or perhaps a workaround? This is completely ruining my sales pitch to my boss! D:

**Comment by BelkacemAyachi** [comment]
you can modify the opts at the beginning of the chart javascript code. Add it right after the data is in, for me position 8 was suitable: opts.width=1000 sets the width at 1000px.
