### ISSUE TITLE
Insert custom marker icons in a leaflet map

### ISSUE THREAD

**Issue by sckott** [ramnathv/rCharts#301]
Hey @ramnathv  - Curious how to use custom icons in a leaflet map. I think I got it  except for I don't know where to define the new icon:

``` javascript
var LeafIcon = L.Icon.extend({
    options: {
        shadowUrl: 'leaf-shadow.png',
        iconSize:     [38, 95],
        shadowSize:   [50, 64],
        iconAnchor:   [22, 94],
        shadowAnchor: [4, 62],
        popupAnchor:  [-3, -76]
    }
});
```

Which I can then use e.g., by 

``` javascript
var points = L.geoJson(labels, {
        pointToLayer: function (feature, latlng) {
            return L.marker(latlng, {icon: LeafIcon });
        }
});
```

Where can I define in a new icon var?

**Comment by pfuhlert** [comment]
Any help with multiple icons? The code above does not work for me. $geoJson does not append the new icons, but overwrites the old ones.

**Comment by miguelfg** [comment]
Sorry, I've never managed :-(
