### ISSUE TITLE
Highcharts not working with shiny server

### ISSUE THREAD

**Issue by chrizzl** [ramnathv/rCharts#304]
In dev branch, the highcharts plots are not displayed, if shiny server is used. If shiny is started local it works fine.

Used example:

``` S
# server
library(rCharts)
shinyServer(function(input, output){
    output$myChart <- renderChart2({
      h1 <- Highcharts$new()
      h1$series(data = c(1, 3, 2, 4, 5))
        h1$set(dom = "myChart")
      return(h1)
    })
})
# ui
require(rCharts)
shinyUI(
  mainPanel(
    showOutput("myChart", "Highcharts")
  )
)
# start 
require(shiny)
require(rCharts)
runApp("...")
```

**Comment by rishi-agrawal** [comment]
Hi Ramnath,
In my app I am using a data frame from which I am plotting highcharts. I have deployed it on a server and now I am unable to see the plot as said by chrizzl. I didn't fully understand chrizzl's solution. It would be of great help if you could throw some light on it.

**Comment by ramnathv** [comment]
Do you have reproducible code that you can share?
