### ISSUE TITLE
rChart size control

### ISSUE THREAD

**Issue by trinker** [ramnathv/rCharts#324]
Ramnath I saw in this post [HERE](http://stackoverflow.com/a/20713645/1000343) you have a method for controlling the rChart size within the Rmd file.  Nice.  However this approach messes with other iframes that are embedded within the document.  I have a possible workaround where you give a class to the rCharts `iframe` tag that leaves other iframes untouched.

**Currently...**

```
<iframe src='
figure/nvd3plot2.html
' scrolling='no' seamless></iframe>

<style>iframe{ width: 100%; height: 400px;}</style>
```

**Proposed...**

```
<iframe class="rchart" src='
figure/nvd3plot2.html
' scrolling='no' seamless></iframe>

<style>.rchart{ width: 100%; height: 400px;}</style>
```

**Comment by samssan** [comment]
I have this problem in my shiny app (it scales all the charts to the size of the last chart of my shiny server script) and can't seem to figure out where to insert the

iframe.rChart{ 
  width: 100%; 
  height: 400px;
}

I have already tried  
chartOutput("n1","nvd3"),tags$style(type = "text/css","iframe.rChart {width: 100%; height: 300px; }")

and

n1$setTemplate(afterScript = '<style> iframe.rChart {width: 100%; height: 300px; } </style>')

Any help greatly appreciated!
