### ISSUE TITLE
Cannot Successfully Install rCharts from Github

### ISSUE THREAD

**Issue by z3r0326** [ramnathv/rCharts#333]
I am installing rCharts on R v.3.0.2 x64, Windows 8.  I've been using the following command to install through Github: 

``` S
require(devtools)
install_github('rCharts', 'ramnathv')
```

The output in my Console is as follows:

``` S
Installing github repo rCharts/master from ramnathv
Downloading rCharts.zip from https://github.com/ramnathv/rCharts/archive/master.zip
Installing package from C:\Users\Michael\AppData\Local\Temp\RtmpG2eS9Y/rCharts.zip
Installing rCharts
"C:/Program Files/R/R-3.0.2/bin/x64/R" --vanilla CMD INSTALL  \
  "C:\Users\Michael\AppData\Local\Temp\RtmpG2eS9Y\devtools10745353545d\rCharts-master"  \
  --library="C:/Users/Michael/Documents/R/win-library/3.0" --install-tests 

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)
```

There is a similar issue being reported through stackoverflow (http://stackoverflow.com/questions/20748937/problems-installing-rcharts) but no solution has been posted.  I just did a test of installing ggplot2 through Github, and receive a similar error. ( 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.)  The problem may be with devtools, then, but I figured I would post here first. 

Any assistance would be greatly appreciated.

**Comment by a517dogg** [comment]
just wanted to note that I had pretty much the same problem (except with rsconnect), followed z3r0326's instructions and everything is now fixed. Thanks!
