### ISSUE TITLE
how to horizontal or vertical lines to a plot in rPlot

### ISSUE THREAD

**Issue by jiakm** [ramnathv/rCharts#356]
Hi, I created a scatterplot using rPlot. I am wondering, how i could add a reference line (e.g. horizontal or vertical or y=x line) to the plot. Use p1$layer?
Thanks

**Comment by giorjet** [comment]
I am pretty new to R... so forgive me. I'm trying to add  horizontal and vertical lines in a hplot in a revealjs presentation.
I tried to modify the code above:
 
`
require(xlsx) 
library(rCharts)

Perhplot.df <- read.xlsx("C:\\RDirectory\\AREALAVORO\\JOB\\LaRochePossay2016\\RISULTATI2.xlsx", sheetName="completo2")

lDf <- split(Perhplot.df, Perhplot.df$variable)




h16 <- hPlot(protection ~ days, data = lDf$Exposure, 
            type = "bubble", 
            group = "label",
            title = "By Days of Exposure", 
            subtitle = "Move the mouse pointer on the bubbles to view the data",
            size = "cluster_size", 
            group = "label")
h16$set(width = 1000, height = 600)



ord <- c("Less than 1 week"=0,
"1-2 weeks"=1,
"3-4 weeks"=2,
"More than 4 weeks"=3,
"Mean"=4
)
h16$params$series <- lapply(h16$params$series, function(d){
  temp = ord[d$name]
  names(temp) = NULL
  d$legendIndex = temp
  return(d)
})
h16$yAxis(min = 35, max = 70, title = list(text = "Level of Protection"))
h16$xAxis(min = 0, max = 45, title = list(text = "Days of Exposure"))

dfy<-data.frame(y=c(35,58,70), x=c(18.8,18.8,18.8))
h16$layer(y~x,data=dfy,type="line",color=list(const = 'darkblue'))

h16$show('inline', include_assets = TRUE)

`

the bubble plot is ok but then I try to add the vertical line I have this error:

`Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : ‘layer’ is not a valid field or method name for reference class “Dimple”`

Could Someone help me?

**Comment by giorjet** [comment]
Actually... the error was:

`Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : ‘layer’ is not a valid field or method name for reference class “Highcharts”`

**Comment by ramnathv** [comment]
The `layer` method is not available for `highcharts`. It is specific to the `rPlot` function that makes use of `polycharts`.

**Comment by giorjet** [comment]
thank you ramnathv... any other way to add lines in a highcharts?
