### ISSUE TITLE
Controlling y Axis Scale with Rcharts NVD3 charts

### ISSUE THREAD

**Issue by heathermkrause** [ramnathv/rCharts#361]
Hi.  I love this R package - it's really wonderful. So far I'm unable to figure out a way to control the scale of the y axis in nPlot type 'multiBarChart'.  I'd like to set a lot of the y axes to go from 0 to 100 so they can be standardized across multiples.  Does anyone have any suggestions?  Thanks.

**Comment by kilimba** [comment]
Awesome, saved me some hair loss!

**Comment by vishwadil07** [comment]
Hey Ramnath,

How we will do the same thing in 

Chart1 <- mPlot(x = "Date", y = "LTR", type = "Line", data = sales.char)

PS: y value ranges from 0 to 11

**Comment by lalitgill** [comment]
Hi Ramnath,
can i add horizontal straight line and benchmark to this code
library(rCharts)
hair_eye = as.data.frame(HairEyeColor)
p2 <- nPlot(Freq ~ Hair, group = 'Eye', data = subset(hair_eye, Sex == "Female"), type = 'multiBarChart')
p2$chart(color = c('brown', 'blue', '#594c26', 'green'))
p2$chart(forceY = c(0, 100))
p2

Regards,
Lalit
