### ISSUE TITLE
Saving (standalone) inline html of rCharts plot with knitr 

### ISSUE THREAD

**Issue by mdehollander** [ramnathv/rCharts#373]
Based on the code at http://bl.ocks.org/ramnathv/raw/8084330/ I am trying to save the html code for a plot. I would like to use inline code, however the save() function writes the full html to disk. I managed to save the inline code to a file by using sink(), but this feels more like a hack. Is there a native method to write the inline html to disk?

Furthermore the show() function does not accept the standalone argument. Can this also be added to this function?
[code]

> n1$show('inline', include_assets=TRUE, standalone=TRUE)
> Error in add_lib_assets(lib, ...) : unused argument (standalone = TRUE)
> n1$show('inline', include_assets=TRUE, cdn=TRUE)
> [/code]

Thanks a lot!

**Comment by ribery77** [comment]
I tried to do this the way you describe it    ```{r results = 'asis', comment = NA, cache = F}
library(rCharts)
n1 <- nPlot(mpg ~ wt, data = mtcars, type = 'scatterChart')
n1$show('inline', include_assets = TRUE, cdn = TRUE)
```        but the plot is not shown when

**Comment by englianhu** [comment]
```
suppressMessages(library('rCharts'))

dt1 <- dTable(corpUS, sPaginationType = "full_numbers", iDisplayLength = 10, sScrollX = "100%")

## http://bl.ocks.org/ramnathv/raw/8084330/
dt1$show('iframesrc', cdn = TRUE)
#'@ dt1$show('inline', include_assets = TRUE) #keep loading but unable display anything
#'@ dt1$show('inline', include_assets = TRUE, cdn = TRUE) #blank table frame shown
```

is works for me.
http://bl.ocks.org/ramnathv/raw/8084330/
