### ISSUE TITLE
Format dimple axis with a function?  

### ISSUE THREAD

**Issue by walkerke** [ramnathv/rCharts#421]
I'm currently working on a project to develop interactive population pyramids using rCharts.  These charts require some of the population values to be negative numbers; however, I want all of the values on the population axis to show absolute values, not the negative values in the data.  

I have figured out how to do this correctly with Highcharts and NVD3 by passing a JS function to the axis's properties.  However, I can't figure out how to do this with Dimple (which is the library I am most interested in due to its Storyboard property).  

For clarification, I've included a reproducible example here: http://dl.dropboxusercontent.com/s/waqm14a72s32mog/pyramid_example.html.  

I'm going to keep working to figure this out myself, but I thought I'd ask here as well in case someone with more JS experience than myself has a quick fix.  

Thanks for all your work on this package, it is really incredible!

**Comment by walkerke** [comment]
Closing this - anyone reading this should move to the rcdimple package and see this RPubs: http://rpubs.com/walkerke/india_pyramid

**Comment by ramnathv** [comment]
Thanks for updating the issue @walkerke. `rcdimple` is the way to go.
