### ISSUE TITLE
Error in file(con, "w") : cannot open the connection

### ISSUE THREAD

**Issue by tran3690** [ramnathv/rCharts#462]
Hello,

This relates to the error in the link below:

https://github.com/ramnathv/slidify/issues/299

I checked the solution and fixed my code from using the recommendation of loading knitr package explicitly. 

``` r
require(rCharts)
require(knitr)
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, 
            type = 'multiBarChart')
n1$show(cdn = TRUE)
```

Then i got the new error 

![image](https://cloud.githubusercontent.com/assets/8033068/3439056/2e3441f4-00db-11e4-9273-b61a10cf6022.png)

Which I cannot seem to find the solution for. Notice i tried to run the code below in 
the regular R script and it works fine 

``` r
require(knitr)
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, 
            type = 'multiBarChart')
n1$show(cdn = TRUE)
```

![image](https://cloud.githubusercontent.com/assets/8033068/3439095/1e242b5c-00dc-11e4-8248-aa3a9144bdc3.png)

Another issue I'm facing which i'm not sure if i should open a separate thread is that i notice the R notebook no longer works in the latest release of RStudio (Version 0.98.945). 

```
require(rCharts)
open_notebook()
```

![image](https://cloud.githubusercontent.com/assets/8033068/3439102/741b4cfc-00dc-11e4-817a-ff7e8a665b9f.png)

I tested it on version 0.96.225 and it works fine. 
I wonder if anyone could help with these issues. 

Thank you very much for reading my post! And rCharts rocks! :)

**Comment by 11guptagiriraj** [comment]
I am writing to information mining from Twitter..
after all steps, at last during handshaking, I am getting this error as:

> twitCred <- OAuthFactory$new(consumerKey=consumerKey,
+                              
+                              consumerSecret=consumerSecret,
+                              requestURL=requestURL,
+                              accessURL=accessURL,
+                              authURL=authURL)
> 
> twitCred$handshake(cainfo="cacert.pem")
To enable the connection, please direct your web browser to: 
https:/api.twitter.com/oauth/authorize?oauth_token=lio2StTSAjSHH8jie1TgpdtgeLKuS9TS
When complete, record the PIN given to you and provide it here: 2960112
> setup_twitter_oauth(consumerKey,consumerSecret,accessToken,accessScret)
[1] "Using direct authentication"
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: 1
Adding .httr-oauth to .gitignore
Error in file(con, "w") : cannot open the connection
In addition: Warning message:
In file(con, "w") : cannot open file '.gitignore': Permission denied.


I wonder if anyone please help to fix this issues.

Thanks in advance.

**Comment by ramnathv** [comment]
This question does not relate to `rCharts`.

**Comment by martinbel** [comment]
After trying the previous examples, using the python simple server worked. So to just make it reproducible:

1. Create a new .Rmd document
2. Insert this example code: 

---
title: "01viz"
author: "whoever"
date: "30 de diciembre de 2015"
output: html_document
---

```{r results = 'asis', comment = NA}
library(rCharts)
r1 <- rPlot(mpg ~ wt, data = mtcars, type = 'point')
r1$show('iframesrc', cdn = TRUE)
```

3. Hit the Knit R HTML button in RStudio. 
4. Open a terminal in the folder where the .html document created is and start a web server:
python -m SimpleHTTPServer
5. Open Chrome/Firefox and type: http://localhost:8000, then navigate until finding the html document created, in this case: http://localhost:8000/01viz.html
6. It should look something like this:
![image](https://cloud.githubusercontent.com/assets/4535400/12053661/11578e6e-aefa-11e5-8154-4325f687ede5.png)

**Comment by jinglingca** [comment]
My HTML can't embed rchart plot. Can you help me with it?

code:

```{r results='asis',comment = NA}
library(knitr)
library(rMaps)
library(rCharts)

i3 <- ichoropleth(Crime ~ State, data = subset(violent_crime, Year == 2010),
                  geographyConfig=list(popupTemplate="#!function(geo, data) {
                                       return '<div class=\"hoverinfo\"><strong>'+
                                       data.State+
                                       '<br>' + data.Crime+
                                       '</strong></div>';}!#"))
i3$show("iframesrc", cdn = TRUE)  
```

HTML output:(no plot embeded)

i3 <- ichoropleth(Crime ~ State, data = subset(violent_crime, Year == 2010),
                  geographyConfig=list(popupTemplate="#!function(geo, data) {
                                       return '<div class=\"hoverinfo\"><strong>'+
                                       data.State+
                                       '<br>' + data.Crime+
                                       '</strong></div>';}!#"))
i3$show("iframesrc", cdn = TRUE)
