### ISSUE TITLE
Rchart in interactive documents: options(rcharts.cdn = TRUE)

### ISSUE THREAD

**Issue by RossiLorenzo** [ramnathv/rCharts#463]
I'm creating a dashboard with the new R Markdown dynamic documents generator.

I created a few shiny apps that use your awesome rCharts package with the highcharts library and I included them in the .Rmd file. I then deployed to my shinyapps.io account.
All the plots/apps work fine except one. In fact the automatic rescaling of the x/y-axis in a multi-line plot does not work if a series is activated/deactivated.

I found this stackoverflow question: 
http://stackoverflow.com/questions/21392362/rcharts-shows-limited-functionality-when-used-with-shiny-0-8-0-99
and tried to add the options(rcharts.cdn = TRUE) as you suggested and the result is the following:
- Locally the problem is fixed and the rchart is fully working
- When deploying to my shinyapps.io account no plot appears. Also all the other plots that were fully working before completely disappeared.

Do you have any suggestion?

**Comment by pfuhlert** [comment]
I have a file that does not display my graph, but when i e.g. change the 

<script src='//... </script>

to

<script src='http://... </script>

It works well. Any suggestions?

http://stackoverflow.com/questions/30194097/after-upgrading-rcharts-not-working-in-rmarkdown
