### ISSUE TITLE
nvd3 rescaling both y axes in multiChart

### ISSUE THREAD

**Issue by liuchbryan** [ramnathv/rCharts#477]
Hi, I am playing with nvd3 multiChart and is clueless on how to scale the y axes, my example is based on that shown [here](http://rcharts.readthedocs.org/en/latest/nvd3/create.html#multi-chart):

Dataset:

``` r
> test
         Date Item    value
1  2014-07-15    x 33210.28
2  2014-07-16    x 44388.01
3  2014-07-17    x 39883.45
4  2014-07-18    x 27654.11
5  2014-07-19    x 33200.70
6  2014-07-20    x 31779.71
7  2014-07-15    y  3924.14
8  2014-07-16    y  4602.90
9  2014-07-17    y  4171.40
10 2014-07-18    y  4146.44
11 2014-07-19    y  4880.00
12 2014-07-20    y  4732.50
13 2014-07-15    z    88.18
14 2014-07-16    z    89.63
15 2014-07-17    z    89.54
16 2014-07-18    z    85.01
17 2014-07-19    z    85.30
18 2014-07-20    z    85.11
```

Graph plotting code:

``` r
plot <- nPlot(value ~ Date,
              data = test,
              group = "Item",
              type = 'multiChart')

#Set which axes the item should follow
plot$params$multi <-
  list(x = list(type="bar", yAxis = 1),
       y = list(type="bar", yAxis = 1),
       z = list(type="line", yAxis = 2))

#Format xAxis from R date format to JS time format
#Printed as dd-mm-yyyy
plot$xAxis(tickFormat="#!function(d) {return d3.time.format('%d-%m-%Y')(new Date( d * 86400000 ));}!#")

plot$setTemplate(script = system.file(
  "/libraries/nvd3/layouts/multiChart.html",
  package = "rCharts"
))

plot
```

And the resultant graph looks like this:
![multichart](https://cloud.githubusercontent.com/assets/6681599/3656239/2798dee0-1184-11e4-9195-681926f9095b.png)

As you can see the scaling for both the y axes is not ideal and I would like to rescale it, though the closest help post I could find is #361, which is not quite helpful in this case.

Kindly see if there are any workarounds, thank you!

**Comment by abhy3** [comment]
Hi @timelyportfolio,

The z-axis line is not hiding upon selecting the z-axis filter, only labels are hidden. Any solution for that?
