### ISSUE TITLE
Support for Highcharts drilldown.js

### ISSUE THREAD

**Issue by mdehollander** [ramnathv/rCharts#479]
I noticed that the drilldown example (#9) is not working properly. According to the Highcharts API there is module for this (http://api.highcharts.com/highcharts#drilldown). Would it be possible to support the drilldown.js module? This module is not yet included in `inst/libraries/highcharts/config.yml`

The development of this module can be seen here: https://github.com/highslide-software/highcharts.com/commits/master/js/modules/drilldown.src.js, with readable source http://github.highcharts.com/modules/drilldown.js and mini code http://code.highcharts.com/modules/drilldown.js

This is what you can do with it for example: http://jsfiddle.net/highcharts/Vf3yT/. I was thinking to create a stacked bar chart with drilldown into n-levels. I am not sure what is needed to get this working with rCharts, and how to get the data correctly imported, but if there is anything I can do, please let me know.

**Comment by csese** [comment]
I would like to know if you have made any improvement on the drilldown feature? 

Thank you for this package. I love it.

**Comment by trinityluo** [comment]
I'm still looking forward to have the drilldown feature in rChart. Any updated info?

**Comment by pssguy** [comment]
Does highcharter offer this functionality?

**Comment by trinityluo** [comment]
Yes, they do have this functionality. Thank you for point it out.
