### ISSUE TITLE
rCharts sizing and overlapping issue within Shiny App

### ISSUE THREAD

**Issue by ConnieZ** [ramnathv/rCharts#511]
Hi Ramnath, thanks again for a great product, I'm enjoying rCharts very much.

I am not sure if this is issue is more to do with Shiny or rCharts, so please let me know.
I've been working on a Shiny App/dashboard for the past month and most of my charts use Highcharts library. I often have more than one chart per page, besides I'm using navbarPage with several navbarMenus. So the issue I'm having is when I go between "pages" of the navbarPage the charts often overlap each other, which obviously doesn't look very good. Another issue I'm having is I can't seem to size the charts consistently (let me know if that deserves its own ticket). 
I've tried using div(class='wrapper',tags$style(".highcharts{ height: 600px; width: 700px}"), which seemed to help for a single chart but not when there's more than one, it seems. Also because
the charts are dynamic and depend on user input, they sometimes don't look very good within these set parameters, so I started changing 600px for height to be 100%, and that seemed to solve the issue with showing content appropriately, but that doesn't solve the overlapping issue when I go between pages of the app. I'm worried that maybe having the navbarPage format
of the app caises the charts' size settings to get mixed up.
And a subissue of that is that width setting doesn't seem to work, I am trying to create a margin on the right, but the chart still takes 
all the space in the mainPanel.

To demonstrate these issues I am adding pictures here with my app.
First the overlapp issue. You can see 3 pictures: before leaving the page, all three charts are displayed normally, one after the other; then I visit the second page, with 2 other plots, and then I come back to the first page and now the second chart (pie) is in the middle of the first chart. 
![overlapping](https://cloud.githubusercontent.com/assets/4405170/4066075/b826b4ce-2e20-11e4-8495-1853b5b012a6.jpg)

Why is that? Is it something that Shiny is doing? Is there a way to separate the charts? FluidRow doesn' seem to do the trick.

The second issue with resize can be seen here.
But I'm also documenting the fact that sometimes charts don't show up unless you add this line
div(class='wrapper',...)

Why is that?

Here's scenario 1: None of the charts are displayed, even though both were supposed to be displayed on both Tab 1 and Tab2, please see the code below:

```
#ui.R
library(rCharts)
library(shiny)

options(rcharts.cdn = TRUE)
shinyUI(navbarPage("Test Dashboard",
        tabPanel("Main", sidebarLayout(
                sidebarPanel(
                      helpText("Text")
                      ),
                      mainPanel(      
                                #nothing here
                      )
                )
         ),               
         navbarMenu("Menu",
                tabPanel("Test Menu 1", sidebarLayout(
                      sidebarPanel(
                           helpText("Test")
                      ),
                      mainPanel(
                           showOutput("chart1", "highcharts")
                           ,
                           br(), br(), br(), 
                           showOutput("chart2", "highcharts")
                      ))) ,
                tabPanel("Test Menu 2",sidebarLayout(
                      sidebarPanel(
                           helpText("Test")
                      ),
                      mainPanel(
                           showOutput("chart2", "highcharts")
                           ,
                           br(), br(),
                           showOutput("chart1", "highcharts")
                      )))
          )))

#server.R

require(rCharts)
library(shiny)

shinyServer(
  function(input, output) {
    output$chart1 <- renderChart({
      a <- hPlot(mpg ~ wt, data = mtcars, type = 'scatter', group = 'cyl', radius = 6, group.na = "Not Available")
      a$colors('rgba(223, 83, 83, .5)', 'rgba(119, 152, 191, .5)', 'rgba(60, 179, 113, .5)')
      a$legend(align = 'right', verticalAlign = 'top', layout = 'vertical')
      a$plotOptions(scatter = list(marker = list(symbol = 'circle')))
      a$tooltip(formatter = "#! function() { return this.x + ', ' + this.y; } !#")
      a$addParams(height = 100, width = 300, dom="chart1")
      return(a)
    })

    output$chart2 <- renderChart({
      a1 <- hPlot(mpg ~ wt, data = mtcars, type = "bubble", title = "Zoom demo", subtitle = "bubble chart", size = "cyl", group = "am")
      a1$chart(zoomType = "xy")
      a1$exporting(enabled = T)
      a1$addParams(height = 500, width = 200, dom="chart2")
      return(a1)
    })
 })
```

Here's scenario 2: if I comment out the charts on the second Tab, called "Test Menu 2", then the charts on the first Tab, called "Test Menu 1", will show up, however the size parameters I specified in server.R (a$addParams(height = 100, width = 300, dom="chart1")) don't seem to apply, as you can see the charts proportionally take the whole mainPanel up and are the same in size pretty much. 

![scenario2](https://cloud.githubusercontent.com/assets/4405170/4066085/ce7df246-2e20-11e4-9727-c9d2172d4970.jpg)

Why didn't the settings work?

Here's scenario 3, that I tried: if I leave the second Tab's chart commented out, and then add the div(class=wrapper...) code to the charts in the first Tab in order to try and control the size features of them, as in the below code, the charts look exactly the same as in the picture above, which means that the div(class=wrapper...) doesn't work for sizing either:

```
div(class='wrapper',tags$style(".highcharts{height: 100px, width: 300px}"),
    showOutput("chart1", "highcharts"))
,
br(), br(), br(), 
div(class='wrapper',tags$style(".highcharts{height: 500px, width: 200px}"),
    showOutput("chart2", "highcharts"))
```

Why isn't that working and what can be done to control the size (and/or perhaps add margin on the right). What am I possibly doing wrong? Can this perhaps be because navbarMenu is by default a fluidPage kind of layout in Shiny and therefore, the size has to be flexible and depend on the size of the screen? I really like that idea, but how do I at least add the margin on the right and prevent overlapping of charts? 

Btw, scenario 4: if I add div(class="wrapper",...) to all charts, not commenting them out, then no charts appear at all.

Do I need to load some css style sheet? Please advise. Sorry it's such a long explanation, but I tried to make it detailed and sufficient. Please let me know if you need my session info.

Thanks again for all your help,

Connie

**Comment by jmoore24** [comment]
Hey guys did this ever get solved?

**Comment by ConnieZ** [comment]
Hey, moore24. I have used some workarounds for this issue in the past - setting the sizes explicitly for each chart, like here mychart$chart(height=300, width=400); or by using the div() workaround shown above. There's now a package called shinydashboard, that uses Boxes and unless you set up the height and width explicitly, the charts seem to stay within the limits of the box, however, you may have to adjust using the chart() function above if you want smaller sizes. I've found that if you have dynamic content (for instance from using input$...), you can make the size of the chart adjust dynamically by passing a variable for height and width instead of a number. Hope this helps, let me know if you have more problems and what kind specifically.

**Comment by jmoore24** [comment]
Thanks Connie!

**Comment by jmoore24** [comment]
An alternative is to set multiple axis and just have them shifted within the same chart.

Example code below.

```r
sharePricePlot2 <- function(data){
        data <- na.exclude(data)
        data <- transform(data, date = as.numeric(as.Date(date)) * 86400000)
        a <- rCharts::Highcharts$new()
        a$yAxis(list(
                list(title = list(text = "Share Price"),max = max(data$close)*1.05,opposite = TRUE,height = 400,
                     labels = list(
                             style = list(
                                     fontWeight = "bold")
                     )
                ),
                list(title = list(text = "MACD"),opposite = FALSE, 
                     top = 425,offset = 0,height = 100,
                     labels = list(
                             style = list(
                                     fontWeight = "bold")
                     )
                ),
                list(title = list(text = "CHAI"),opposite = TRUE, plotBands = list(color = "black",from = 100, to = 110), 
                     top = 550,offset = 0,height = 100,
                     labels = list(
                             style = list(
                                     fontWeight = "bold")
                     )
                ),
                list(title = list(text = "Elder"),opposite = FALSE, 
                     top = 675,offset = 0,height = 100,
                     labels = list(
                             style = list(
                                     fontWeight = "bold")
                     )
                )
        )
        )
        
        a$xAxis(type = "datetime")
        
        a$series(type = "line",name = "Share Price",
                 data = toJSONArray2(data[,c("date","close")],json = F,names = F),
                 color = "orange"
        )
        
        a$series(type = "line",name = "MA",
                 data = toJSONArray2(data[,c("date","MA")],json = F,names = F)              
        )
        
        a$series(type = "line",name = "EMA",
                 data = toJSONArray2(data[,c("date","EMA")],json = F,names = F)              
        )
        a$series(type = "line",name = "BollUp",
                 data = toJSONArray2(data[,c("date","up")],json = F,names = F),
                 color = "red"              
        )
        a$series(type = "line",name = "BollDn",
                 data = toJSONArray2(data[,c("date","dn")],json = F,names = F),
                 color = "red"              
        )
        
        a$series(type = "line",name = "Bollavg",
                 data = toJSONArray2(data[,c("date","mavg")],json = F,names = F),
                 color = "red"
        )
        
        
        a$series(type = "line",name = "MACD",
                 data = toJSONArray2(data[,c("date","MACD")],json = F,names = F),
                 yAxis = 1
        )
        
        a$series(type = "line",name = "SIGNAL",
                 data = toJSONArray2(data[,c("date","SIGNAL")],json = F,names = F),
                 yAxis = 1
        )
        
        a$series(type = "line",name = "CHAI/1000",
                 data = toJSONArray2(data[,c("date","Chai")],json = F,names = F),
                 yAxis = 2
        )
        
        a$series(type = "line",name = "CHAI SMA/1000",
                 data = toJSONArray2(data[,c("date","chaiSMA")],json = F,names = F),
                 yAxis = 2
        )
        
        a$series(type = "line",name = "Elder Bear",
                 data = toJSONArray2(data[,c("date","Bear")],json = F,names = F),
                 yAxis = 3             
        )
        
        a$series(type = "line",name = "ElderBull",
                 data = toJSONArray2(data[,c("date","Bull")],json = F,names = F),
                 yAxis = 3              
        )
        
        
        a$tooltip(crosshairs = list(T,F),
                  shared=TRUE,
                  formatter = "#! function() { 
                   var d = new Date(this.x);
                   d = d.toLocaleDateString();
                   d = '<strong>' + d + '</strong>';
                   $.each(this.points,function(){
                   d += '<br>' + this.series.name + ': ' + '<strong>' + this.y + '</strong>';
                   })
                   return (d);
                   }!#"
        )       
        
        
        a$legend(align = "right",verticalAlign = "center", 
                 layout = "vertical",itemMarginTop = 10,x = 10,
                 floating = FALSE,backgroundColor = "white")
        
        a$plotOptions(series = list(pointPadding = 0,groupPadding = 0.2,marker = list(enabled=FALSE)))
        a$chart(width = 1200, height = 825,plotBorderWidth = 0.5,plotBorderColor="black")
        a
        
}
```
