### ISSUE TITLE
nPlot stacked option not working

### ISSUE THREAD

**Issue by ssridhar21** [ramnathv/rCharts#545]
Hey Ramnathv, I'm running into a few issues with a nvd3 plot I'm making. 
1) the stacked option is not working
2) How can I resize the plot area to fit the axis labels? Specifically, the y-axis and x-axis labels are getting cut off

Any input you might have would be greatly appreciated.

Thanks!
Sri

Here's the plot code:
n2 <- nPlot(C3 ~ C2, group = 'C1', 
            data = test, type = 'multiBarChart')
n2$yAxis(axisLabel = 'Value (in thousands)')
n2$xAxis(axisLabel = 'Category')
n2$templates$script <- "http://timelyportfolio.github.io/rCharts_nvd3_templates/chartWithTitle_styled.html"
n2$set(title = "Value by Category Across Groups")
n2$chart(reduceXTicks = FALSE)
n2$xAxis(rotateLabels=-45)
n2$yAxis(axisLabel = "Total Value (In Thousands)", width = 40)
n2$yAxis(rotateLabels=-90)
n2$set(width = 800, height = 600)
n2

Here's the data frame:

> test
>      C1         C2           C3
> 1    G1  category1 2.155007e+05
> 2    G1  category1 9.952324e+04
> 3    G1  category1 3.091145e+05
> 4    G1  category1 1.352964e+05
> 5    G1  category1 1.420613e+03
> 6    G5  category1 1.046033e+05
> 7    G6  category1 7.067042e+02
> 8   G12  category1 2.057110e+02
> 9   G15  category1 3.537396e+05
> 10   G4  category2 2.142554e+05
> 11   G5  category2 1.181017e+05
> 12   G5  category2 1.497603e+05
> 13   G5  category2 2.027308e+05
> 14   G5  category2 1.938218e+02
> 15   G8  category2 2.849902e+02
> 16  G14  category2 1.995722e+05
> 17   G1  category3 1.343549e+05
> 18   G2  category3 1.489214e+05
> 19   G5  category3 5.168491e+02
> 20   G5  category3 4.393116e+02
> 21   G6  category3 1.293348e+03
> 22   G8  category3 1.024978e+03
> 23  G11  category3 2.800216e+02
> 24  G11  category3 2.209898e+05
> 25  G11  category3 1.182365e+05
> 26  G11  category3 9.486837e+04
> 27  G11  category3 1.561002e+05
> 28  G11  category3 1.044707e+05
> 29  G11  category3 2.558965e+02
> 30  G11  category3 4.355196e+02
> 31  G15  category3 1.073320e+05
> 32  G17  category3 1.618801e+05
> 33   G5  category4 1.001675e+05
> 34  G10  category4 9.919390e+05
> 35  G10  category4 1.210753e+05
> 36   G2  category5 2.556647e+06
> 37   G5  category5 5.737914e+02
> 38   G5  category5 5.363085e+02
> 39   G6  category5 2.792469e+05
> 40   G8  category5 1.139726e+05
> 41   G8  category5 5.333164e+02
> 42  G11  category5 1.545037e+05
> 43  G11  category5 1.153698e+02
> 44   G1  category6 7.747291e+04
> 45  G17  category6 6.226229e+02
> 46   G1  category7 1.621620e+05
> 47   G2  category7 8.332909e+04
> 48   G3  category7 1.556204e+05
> 49   G3  category7 7.621068e+02
> 50   G7  category7 1.650015e+05
> 51   G8  category7 7.454845e+04
> 52  G11  category7 7.997187e+04
> 53  G11  category7 2.652086e+02
> 54  G14  category7 1.677926e+05
> 55  G14  category7 1.366086e+05
> 56   G2  category8 3.038695e+05
> 57   G2  category8 3.294948e+05
> 58   G2  category8 6.345305e+05
> 59   G2  category8 9.682755e+04
> 60   G2  category8 6.176700e+04
> 61   G2  category8 5.414136e+02
> 62   G3  category8 7.981411e+04
> 63   G4  category8 9.901349e+04
> 64   G4  category8 1.524643e+05
> 65   G5  category8 1.464986e+05
> 66   G5  category8 1.982908e+02
> 67   G5  category8 1.066529e+03
> 68   G8  category8 1.106762e+05
> 69   G8  category8 4.081732e+03
> 70   G8  category8 3.103437e+02
> 71  G10  category8 1.179692e+05
> 72  G11  category8 8.400501e+04
> 73  G11  category8 3.012282e+02
> 74  G11  category8 1.434943e+02
> 75  G11  category8 1.933331e+02
> 76  G11  category8 2.933822e+02
> 77  G11  category8 4.672613e+02
> 78  G11  category8 3.928661e+02
> 79  G14  category8 1.763966e+05
> 80  G15  category8 1.512523e+05
> 81  G15  category8 2.204592e+05
> 82  G15  category8 1.167566e+03
> 83  G16  category8 2.266650e+05
> 84  G17  category8 1.757096e+05
> 85  G17  category8 7.911540e+04
> 86  G17  category8 7.079436e+02
> 87  G17  category8 1.092000e-02
> 88  G17  category8 2.248865e+02
> 89   G1  category9 1.034090e+05
> 90   G2  category9 2.396326e+03
> 91   G2  category9 3.992297e+04
> 92  G15  category9 2.728013e+05
> 93  G16  category9 1.623451e+05
> 94  G17  category9 1.889511e+05
> 95   G1 category10 1.367589e+05
> 96   G1 category10 1.466092e+05
> 97   G2 category10 1.172892e+05
> 98   G2 category10 2.112234e+05
> 99   G2 category10 1.077100e+05
> 100  G3 category10 4.417656e+04
> 101  G3 category10 1.062158e+05
> 102  G3 category10 2.997617e+05
> 103  G5 category10 8.122105e+02
> 104  G5 category10 1.527735e+03
> 105  G5 category10 2.000380e+02
> 106  G5 category10 2.491070e+03
> 107  G9 category10 1.059240e+05
> 108 G10 category10 1.683199e+05
> 109 G11 category10 8.329230e+02
> 110 G11 category10 1.487359e+02
> 111 G11 category10 3.582088e+02
> 112 G11 category10 4.851838e+02
> 113 G13 category10 8.562098e+04
> 114 G14 category10 9.756514e+04
> 115 G14 category10 1.064588e+05
> 116 G17 category10 2.926942e+02

Here's a screenshot of the output:
![image](https://cloud.githubusercontent.com/assets/7018589/4999120/245e0e68-69ad-11e4-8c01-694998d15533.png)

**Comment by rantish** [comment]
Hi Sridhar,

I need to acheieve the same ("add zero counts corresponding to missing groups") - can you please help me out on how you acheive this.

Thanks in advance.

**Comment by zippyjg** [comment]
I have the same problem as rantish, how are you adding zero counts to missing groups?
