### ISSUE TITLE
nPlot (NVD3): tooltip content does not show up

### ISSUE THREAD

**Issue by ghost** [ramnathv/rCharts#547]
The tooltip content of my plot does not appear when I hover over the item. The only way to make it appear is to point my cursor on a point and reload the plot. 

```
require(rCharts)

# data frame
set.seed(1234)
dt <- data.frame(var1=round(runif(10, 0, 100)), var2=round(runif(10, 0, 100)), var3=runif(10, 100, 1000),var4=LETTERS[1:10])

# plot
n1 <- nPlot(var1 ~ var2, data = dt, type = 'scatterChart')
n1$chart(tooltipContent= "#! function(key, x, y, e){
    return '<b>Bezirk</b> ' + e.point.var4 + '<br/>' +
    '<b>Ja x (%):</b>' + e.point.var1 + '<br/>' +
         '<b>Ja y (%):</b>' + e.point.var2
         } !#")
n1$chart(forceY = c(0, 100))
n1$chart(forceX = c(0, 100))
n1$chart(size = '#! function(d){return d.var3} !#')
n1$yAxis(tickFormat = "#! function(d) {return d + '%'} !#")
n1$xAxis(tickFormat = "#! function(d) {return d + '%'} !#")
n1$chart(showControls = FALSE)
n1$chart(showLegend = FALSE)
n1
```

**Comment by jsramos** [comment]
Good, day, everyone. Is this closed because the NVD3 guys refused to address this? Or has it been worked around?

**Comment by jsramos** [comment]
Is there something we could do in R to work around this?

**Comment by basilschlapfer** [comment]
Hi, I closed it because the work around was o.k. for me (see above). I'll be happy to learn anything about a work around in R. I tried but was never succesfull.

**Comment by basilschlapfer** [comment]
As I am not really familiar with GitHub please tell me if I should reopen this issue.

**Comment by jsramos** [comment]
You don't need to reopen. I just wanted to ask if there was a workaround that did not involved tinkering with the generated HTML and that could be implemented directly from R.
