### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by iandunham** [ramnathv/rCharts#58]
I've been playing with rCharts for displaying some data I am working with and it is a really nice implementation. However there are a few refinements I would like to make to the chart, and I can't figure out how to do this.

r1 <- rPlot(Zscore ~ Cell , data=results, color="Zscore", type="point")

gives the attached image

![rcharts](https://f.cloud.github.com/assets/1729980/458904/8aa38352-b3f0-11e2-808a-ca4320fb084f.png)

I'd like to modify this by 
- controlling the plotting area to be bigger than the minimum area of data on the y axis
- labelling all the x axis points, possibly rotating the text to be vertical
- allowing additional data to be available in the mouse over tooltips - I have another 3 data fields that are available that I'd like to inspect.

I couldn't work out this from the doc. Is it possible.

Thanks
ian

**Comment by biadias** [comment]
I tried to use $guides, but I am having an error:
 ‘guides’ is not a valid field or method name for reference class “rCharts”
