### ISSUE TITLE
rCharts

### ISSUE THREAD

**Issue by AlkaGupta1** [ramnathv/rCharts#585]
Hi,

I need to create a dashboard where i have to use a combination of USA map, Zip codes in US and some key metrics for each of those Zip codes.

I started using ggplot and then using latitude and longitude information i could plot the points as well as the state map. I needed to enable the hover in but it seems it is not possible using gglpot.

I switched to rCharts. I am able to get the Zip codes and the hover over feature but i am unable to make USA map in the backgound(i need it by using lat & lat). 
Is there any way of combining a map, points and hover in together using rCharts?
UI:

library(shiny)
library(rworldmap)
require(rCharts)

# Define UI for dataset viewer application
shinyUI(fluidPage(
  
  tags$head(tags$style(HTML(".shiny-text-output {background-color: #d8d8d8}"))),  
  
  h1(img(src="Abc.png",height = 72, width = 72, align = "textleft"),span("Retail Impact on Direct", style = "font-weight: 150"),
     style = "font-family: 'Source Sans Pro';color: #000000; text-align: Center; background-image: url('test1.jpeg');padding: 10px;width=100%",img(src="def.png",height = 75, width = 100, align ="textright")),
  
  hr(SIZE="10"), 

  
  sidebarLayout(position="left",
                
                sidebarPanel(width = 2, h6("Please select : ",Type="Bold"),
                             
                             selectInput(selected='Units',multiple=F, "metric", "Metric",c("Units","Revenue","Margin")),  
                             
                             selectInput(selected='A',multiple=F,"retailStore", "Select # of Retail stores",c('All','1','2','3','4','5','6')),
                             
                             selectInput("YearChosen", 
                                         "Select an Year", 
                                         c('FY-2013','FY-2014','FY-2015'),multiple = F
                                         ,selected = 'FY-2015'),
                             
                             selectInput("monthChosen", 
                                         "Select a Month", 
                                         c('January','February','March'
                                           ,'April','May','June','July','August'
                                           ,'September','October','November','December'),multiple = F
                                         ,selected = 'February'),
                             
                             sliderInput("tomChosen", "Trend Across Months: ", 1, 12, 0,
                                         step = 2, animate=animationOptions(interval = 400, loop= F))
                             
                             
                ),  
                    
    mainPanel(
                      { 
                        
                        #plotOutput("map")
                        showOutput("myChart", "polycharts")                                            
                          
                        
                        })
  )
)
)

Server:
library(shiny)
library(xtable)
library(maps)
require(rCharts)
library(ggplot2)

countries <- read.csv("D:/R-Projects/Retail/Direct_Ret_pop_final4.csv")
State<-read.csv("D:/R-Projects/Retail/StateData.csv")
shinyServer(function(input, output)
  {
  
  observe({
       
    if (input$retailStore == "All")
       {datafilter<-reactive({
         countries[which((countries$Year %in% input$YearChosen
                   #& countries$Month %in% input$monthChosen
                   & countries$Mon_Num %in% input$tomChosen
                   ))                   
                   ,] })
        }
    else
    {
       datafilter<-reactive({
         countries[which((countries$Major.Stores %in% input$retailStore
                          & countries$Year %in% input$YearChosen
                          #& countries$Month %in% input$monthChosen
                          & countries$Mon_Num %in% input$tomChosen
                          ))                  
                   ,] })
      }
       
       #FinalData <- reactive({aggregate(datafilter()$Retail_norm, by=list(datafilter()$Zip), FUN=mean )[,c(1,2)]})   
         
           
       
       
    data<-datafilter() 
    data$colorfill <- ifelse(((data$Retail_Contri) >= 0.0 & (data$Retail_Contri) <0.2) ,"  0-20 %",
                          ifelse(((data$Retail_Contri) >= 0.2 & (data$Retail_Contri) <0.4) ,"  20-40 %", 
                                ifelse(((data$Retail_Contri) >= 0.4 & (data$Retail_Contri) <0.6) ,'  40-60 %',
                                    ifelse(((data$Retail_Contri) >= 0.6 & (data$Retail_Contri) <0.8) ,'  60-80 %',
                                        ifelse(((data$Retail_Contri) >= 0.8 & (data$Retail_Contri) <=1.0) ,'  80-100 %',
                                       "Other")))))
    
    
           
    output$map <- renderPlot({  
      
      p <- ggplot()         
      p <- p + geom_polygon( data=State, aes(x=long, y=lat, group = Group),colour="white", fill="Blue" )
      print(p)  
    })  
    
    
    output$myChart <- renderChart({  
                  
                   #p <- ggplot()         
                   #p <- p + geom_polygon( data=State, aes(x=long, y=lat, group = Group),colour="white", fill="Blue" ) +geom_point( data=data, aes(x=Longitude, y=Latitude, size = Retail_norm ,color= colorfill)) 
      
      
                  p1 <- rPlot(Latitude ~ Longitude, data = data, type = 'point', 
                              size = "Retail_norm" , color = "colorfill", tooltip = "#! function(item){return 'ZIP Code='+ item.Zip+'; Retail Norm='+item.Retail_norm} !#")
                  
      
                  p1$set(height = 450)
                  
                  p1$guides(x = list(title = ""))
                  
                  p1$guides(y = list(title = ""))
                  
                  
                  p1$set(title = 'Retail Impact Data', dom = 'myChart')
                  
                  return(p1)
                          
                            
                                        })  
    
        
        
    
    
    
    })
  })

Any help will be appreciated!!

**Comment by ramnathv** [comment]
You cannot use `polychart` with a `map` like you have done so in your code since they are using different coordinate systems.
