### ISSUE TITLE
New base map on Leaflet

### ISSUE THREAD

**Issue by aruizga7** [ramnathv/rCharts#586]
Hi,

Imagine I want to put the following base map: 

http://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}

How can I do it with RCharts?

I see you have this to specify the base map:

#map3$tileLayer(provider = 'Stamen.TonerLite')

Can I put the url there? If yes...in which format?

Thanks!

**Comment by ramnathv** [comment]
The `tileLayer` method accepts a `url` parameter directly, and you can pass your map layer there.

```r
map3$tileLayer(url = URL)
```

**Comment by aruizga7** [comment]
Thanks that worked perfect :-)

**Comment by ramnathv** [comment]
Great.
