### ISSUE TITLE
Highcharts exporting in Shiny crashes app in Firefox browser

### ISSUE THREAD

**Issue by leonawicz** [ramnathv/rCharts#592]
Inclusion of the export option, e.g., a$exporting(enabled=TRUE), crashes a Shiny app in Firefox, but works fine in Chrome for example. Both browsers up to date, as well as Shiny and rCharts. Testing has been local, multiple computers, but no testing with shiny-server. The following reproduces the problem for me.

ui.R

```
library(rCharts)
shinyUI(bootstrapPage(
    showOutput("chart", "highcharts")
))
```

server.R

```
library(shiny)
library(rCharts)
shinyServer(function(input, output) {
    output$chart <- renderChart2({
        a <- rCharts:::Highcharts$new()
        a$chart(type = "line")
        a$title(text = "A plot")
        a$data(data.frame(x=1:10))
        #a$exporting(enabled=T)
        a$addParams(dom='chart')
        a
    })
})
```

If the exporting line above is uncommented, the app will still run, plot will display, the chart context menu which appears in the upper right corner is functional, but as soon as a download option is clicked the browser grays out, and server side reactivity is terminated (in apps where there is more to do, such as selecting other data sets and replotting). Interestingly, though the app otherwise grays out and must be manually restarted, the plot download still succeeds afterward. This seems to only happen with Firefox.

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rCharts_0.4.5 shiny_0.11   

loaded via a namespace (and not attached):
 [1] digest_0.6.8    grid_3.1.2      htmltools_0.2.6 httpuv_1.3.2   
 [5] lattice_0.20-29 mime_0.2        plyr_1.8.1      R6_2.0.1       
 [9] Rcpp_0.11.4     RJSONIO_1.3-0   tools_3.1.2     whisker_0.3-2  
[13] xtable_1.7-4    yaml_2.1.13
```

**Comment by cocinerox** [comment]
There is a workaround for this issue: you need to pass `formAttributes: {target: '_blank'}` for the `exporting` option. This can be done in `htmlwidgets` - I'm not sure regarding `rCHarts`.

**Comment by leonawicz** [comment]
This does not appear to have any affect on this bug in rCharts.

At least, I am not able to change the behavior by using the line:
<code>p$exporting(enabled=T, formAttributes=list(target='_blank'))</code>

The behavior remains good in Chrome and bugged in Firefox, with or without the formAttributes argument. Perhaps I am specifying it incorrectly?

**Comment by cocinerox** [comment]
Looks like the `rCharts/libraries/highcharts/js/exporting.js` is way too old. If you replace it with a recent version (http://code.highcharts.com/modules/exporting.js) it should work.

**Comment by ramnathv** [comment]
@cocinerox or @leonawicz If you can send me a pull request that updates `exporting.js`, I can merge it in.

**Comment by icarvalhosa** [comment]
@ramnathv any updates on this? 

The export option (a$exporting(enabled=TRUE)) is also crashing my app when it is hosted in shinyapps.io (I use Chrome).
It is a similar problem as leonawicz.
If the exporting line above is uncommented, the app will still deploy, run, plot will display, the chart context menu which appears in the upper right corner is functional, but as soon as a download option is clicked the plot area turn white/blank,

The exporting function works fine locally. 

Any ways to work around this?

**Comment by dylancis** [comment]
I actually the same issue  as @leonawicz - please let me know if there any existing workaround in R.

**Comment by ramnathv** [comment]
Please use the [highcharter](https://github.com/jbkunst/highcharter) package that is based on `htmlwidgets` and is more up-to-date.
