### ISSUE TITLE
X axis not  displayed and spacing of legend

### ISSUE THREAD

**Issue by DAWij** [ramnathv/rCharts#593]
Hi, I am quite new to rCharts and would like some help regarding the following. I am using nPlot to draw a multiple line chart.

1. I have noticed that when the d3 charts are rendered they do not have a x-axis line. However, in examples given both through rCharts and nvd3 (as images) the x-axes are there. 

2. The legend seems cramped up. What can I do to manually set the spacing between factor names in the legend.

Thanks!

**Comment by ramnathv** [comment]
NVD3 charts don't have an x-axis by default. In order to show an x-axis or adjust spacing between factor names in the legend, you will have to fall back on raw D3, which means writing code in javascript. Unfortunately, there is no easy way to do this using NVD3 or R.
