### ISSUE TITLE
Unable to embed rCharts in html

### ISSUE THREAD

**Issue by leonawicz** [ramnathv/rCharts#597]
Example: http://leonawicz.github.io/CommCharts4/cc4lite01.html
Plot region exists but is blank, tested in Firefox and Chrome. Viewing the page source (plot beings at line 120), I am unsure why it does not display. Everything seems to render from Rmd to HTML properly. I even resaved the html replacing the <code>//</code> at the beginning of each sourced script with <code>http://</code> but this had no effect.

I came across this post: http://stackoverflow.com/questions/25519243/graph-made-by-rcharts-cant-insert-into-slidify
which seems too old to be the issue involved here, but also it is not a matter of clicking on the HTML file locally, now that I have uploaded it to the web and continue to see no plot.

The plot works fine straight from R, and also within a Shiny app.

My script has:
<code>\# @knitr embed</code>
<code>p$show("iframesrc", cdn=TRUE)</code>

and my Rmd file has:
<code>\`\`\`{r embed, comment=NA, results="asis", tidy=F}</code>
<code>\`\`\`</code>

I have tried various permutations of options without success, including within global settings:
<code>\`\`\`{r knitr_setup, echo=FALSE}</code>
<code>opts_chunk$set(cache=FALSE, echo=FALSE, eval=TRUE, tidy=TRUE, message=FALSE, warning=FALSE, results="asis", comment=NA)</code>
<code>options(rcharts.mode='iframe', rcharts.cdn=TRUE)</code>
<code>read_chunk("../../code/embed_ex.R")</code>
<code>\`\`\`</code>

 Is it clear what may be wrong from looking at the html page source itself? Could this be related to rendering with the latest version of rmarkdown (e.g., Bootstrap 3) or because I am rendering the Rmd file along with others which generate a multi-page website (e.g., using a master _output.yaml file)?

**Comment by ramnathv** [comment]
The error message in the browser console suggests that the chart is misconfigured. I don't think this has anything to do with displaying the chart as an inline iframe.

**Comment by leonawicz** [comment]
I am able to display the chart with p$show() in Chrome from an interactive R session, or with p$show('server') in Firefox. It is only when I render the Rmd file which references the same object p that something is going wrong. All paths are correct, all chunks render properly, and the data are in the html file. Is there a way to compare the misconfigured chart output with the output that is generated (but not shown) when plotting direct from the R console?

**Comment by ramnathv** [comment]
If you can provide me with a reproducible Rmd file, I can take a look.

**Comment by leonawicz** [comment]
A simple example fails to reproduce the problem:
http://leonawicz.github.io/CommCharts4/test_embed.html

I will have to go in stages from this basic plot up to the plot I am having issues with. Ideally I will find a particular plot option or some feature of the data that when added, continues to plot in R but is not generating a proper html file. I will post something more when I have it. Thanks.

**Comment by ramnathv** [comment]
I think this is connected with this [PR](https://github.com/ramnathv/rCharts/pull/563) that I just merged. Can you reinstall `rCharts` and let me know if it resolves the issue?

**Comment by leonawicz** [comment]
Excellent.
I created this to show where I was having particular problems:
http://leonawicz.github.io/CommCharts4/test_embed.html

And here using the new version following the merged PR, everything is fixed.
http://leonawicz.github.io/CommCharts4/test_embed2.html

Thank you!

**Comment by leonawicz** [comment]
Oops! And of course, with the latter two not initially plotting, I failed to note that I mixed the labels on those two plots. But it all works again.

**Comment by ramnathv** [comment]
Great that you were able to get it working. I am closing this issue, but feel free to reopen it if the problem resurfaces.
