### ISSUE TITLE
JavaScript Libraries Path

### ISSUE THREAD

**Issue by MuhammadSohaib** [ramnathv/rCharts#598]
I am facing a issue with javascript libraries path while creating a hplot and save it in html file if use cdn=true it doesn't include https:\\ which is needed to run the html document otherwise my html doesn't run. I don't want to use the local library path. I want to do it through the internet library path like this http://code.jquery.com/jquery-1.9.1.min.js 
any suggestions ??

**Comment by ramnathv** [comment]
The plot will work if you open the file with a web-server. You should be able to do this using the `servr` package in R or  simply using `python -m SimpleHTTPServer` from the command line.
