### ISSUE TITLE
Name not working, when using pie-chart / highcharts

### ISSUE THREAD

**Issue by emillykkejensen** [ramnathv/rCharts#601]
I'm trying to show a simple pie-chart using highcharts but the name function dosent seem to work? Instead of showing ’number’ as the name of the value it shows ‘Series 1’.

```r
piechart <- hPlot(Freq ~ headline, data = data, type = "pie", name = "number")
piechart $addParams(dom = piechart)
piechart
```

What am I doing wrong?

**Comment by ramnathv** [comment]
Here is how you can do it

```r
library(dplyr)
dat = as.data.frame(HairEyeColor) %>%
  group_by(Sex) %>%
  summarize(Freq = sum(Freq))

library(rCharts)
h1 <- hPlot(Freq ~ Sex, data = dat, type = 'pie')
h1$params$series[[1]]$name = 'number'
h1
```

The idea is that the `name` needs to be added to the `series` object.
