### ISSUE TITLE
nPlot group ordering is according to order of occurrence in data.frame (vs. sorted)

### ISSUE THREAD

**Issue by jwhendy** [ramnathv/rCharts#603]
I just started playing with `rCharts` and think it's amazing -- thanks for all of your efforts. After skimming the examples, I gave a whirl at plotting some data from work and noticed something I consider odd about the group behavior. If you'd like the actual data, I can put it somewhere, but I think this should get the point across:

```
> data <- read.csv("~/Desktop/nPlot-group-labels.csv")
> str(data)
'data.frame':	1140 obs. of  3 variables:
 $ rate: num  10 10 10 10 10 10 10 10 10 10 ...
 $ v   : num  2 14.5 46 103.5 182 ...
 $ t   : num  0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 ...

> unique(data$rate)
[1] 10.0 12.5 15.0 20.0 25.0 30.0 35.0  7.5
```

The code I used to read in a mess of `.csv` files and `rbind` them together must have stuck 7.5 at the tail of the data for some reason. Here's the `nPlot` I created:

```
n <- nPlot(v ~ t, data = data, group = "rate", type = "lineChart")
n$xAxis(axisLabel = "time (s)")
n$yAxis(axisLabel = "velocity (in/s)", width = 50)
n$chart(margin = list(left = 75))
n
```

![2015-03-07_155359](https://cloud.githubusercontent.com/assets/379357/6543466/2f7f2d64-c4e2-11e4-9fb6-f37b394c956e.png)

7.5 gets put all the way on the right, out of logical order. I wondered if it had to do with `numeric` vs. `factor` behavior, so I also tried:

```
data$rate <- factor(data$rate, levels = sort(unique(data$rate)))
[1] 10   12.5 15   20   25   30   35   7.5 
Levels: 7.5 10 12.5 15 20 25 30 35
```

I hoped that the level order would take priority over the data.frame order, but I get the same result. Is there some way to obtain the "intuitive order" one would expect for the group toggle buttons in the plot? Or am I mis-understanding how this works (considering I've been using `rCharts` for about 30min!)?

**Comment by ramnathv** [comment]
If my memory serves me right, `nvd3` treats the grouping variable as categorical and so sorts it lexically (which is why you see 7.5 after 30). I will take a closer look to confirm the same. I will also check to see if it exposes any options to sort differently, or can the same be achieved using raw d3. Thanks for posting this here.

**Comment by jwhendy** [comment]
Thanks for looking into it. Figured that was what was going on ("lexically"... _that_ was the word I was looking for!). I just fiddled with `polycharts` for the first time as well (using `rPlot`) and the same thing occurs with the facets. I used a bigger data set and the facets (sliced by `rate`) are appearing the same (10, 12.5, 15, ... 7.5).

Is this a general `javascript` thing, or would you suspect it's coded into both libraries?

**Comment by ramnathv** [comment]
Well, categories are by definition unordered. So, I am suspecting that is why they are handled that way. Normally, libraries provide a way to modify the sort order, which can then be used to correct these. Note that javascript does not have factors or ordered factors.

**Comment by annoporci** [comment]
without the data I cannot play around with your specific situation, however just a short while back I had a problem like that. I think I had to both re-order the factors and re-order the variables inside the dataframe, something like this:

df$variable <- factor(df$variable, levels = c("A", "B", "C", "D"), ordered = TRUE)  # re-order the factors
df <- df[order(df$variable), ]  # re-order the variables
nPlot(data = df, value ~ Year, group = 'variable', color = 'variable', type = 'stackedAreaChart')

**Comment by jwhendy** [comment]
@annoporci First off, yes! Sorry... I absolutely should have included a reproducible example. I added one below.

To your point, this is exactly what I'm saying above? Typically R will work with factor order, not `data.frame` order. So ideally, I'd be able to use my data as-is and not have to re-arrange it just to get expected/intuitive ordering of groups.

If you collected a bunch of `(x, y)` pairs and wanted to create a scatter plot, I'm assuming you wouldn't do `df <- df[order(df$x), ]` first. You'd expect that the `x` values would put themselves in increasing order automatically.

Here's a reproducible example confirming that it's purely about `data.frame` order (in other words, you shouldn't have to re-order the factors other than this appears to affect the results of `df[order(...), ]`:

```
library(rCharts)
library(reshape2)

x <- 1:10

dat <- data.frame(x = x,
                  y1 = x^2,
                  y2 = x^3)

dat_melt <- melt(dat, id.vars = "x")

# make factor group variable, intentionally making the 10 group
# appear first in the data frame, followed by 7.5
dat_melt$group <- factor(dat_melt$variable, levels = c("y1", "y2"),
                         labels = c("10", "7.5"))

# check levels and see the plot
levels(dat_melt$group)
n <- nPlot(value ~ x, data = dat_melt, group = "group", type = "lineChart")
n

# re-order, check levels, re-plot
dat_melt$group <- factor(dat_melt$group, levels = c("7.5", "10"))
levels(dat_melt$group)  
n <- nPlot(value ~ x, data = dat_melt, group = "group", type = "lineChart")
n

# does factor(..., ordered = T) matter? Doesn't seem to
dat_melt$group <- factor(dat_melt$group, levels = c("7.5", "10"), ordered = T)
levels(dat_melt$group)
n <- nPlot(value ~ x, data = dat_melt, group = "group", type = "lineChart")
n

# how about we re-order the appearance in the data frame?
# levels are still 10, 7.5 (reverse), but the plot is correct
dat_reorder <- dat_melt[order(dat_melt$group), ]
dat_reorder$group <- factor(dat_reorder$group, levels = c("10", "7.5"))
levels(dat_reorder$group)
n <- nPlot(value ~ x, data = dat_reorder, group = "group", type = "lineChart")
n
```

**Comment by annoporci** [comment]
@jwhendy, I have no idea what ``nPlot()`` does under the hood, but I would imagine that the idiosyncrasies of ordering are more likely to originate from the way the ``d3`` library works than from ``rCharts`` (though that's just a guess). You could, for the time being, simply redefine ``nPlot()`` with a couple of lines to re-order the dataframe consistently with the order of the factors, for instance. (which does not answer your question of course)

**Comment by jwhendy** [comment]
@annoporci agreed. Being new to d3 and even newer to rCharts, I just noticed behaviour I thought was atypical for R. Totally agree with you regarding the source of the issue.

I consider the "issue" resolved (mainly that it's not something I was doing wrong). I think ramnathv was perhaps going to take a look, though having a workaround available certainly makes the desired result achievable even if d3 doesn't behave like R on this. Thanks for the comments and I'll go ahead and close this!
