### ISSUE TITLE
Empty plot output with nvd3 + shiny

### ISSUE THREAD

**Issue by jwhendy** [ramnathv/rCharts#608]
I was having issues trying to re-do an existing shiny app of mine with `rCharts/nvd3` vs. my current `ggplot2` code. I was having some snags, so I tried simply reproducing the `rPlot` example of outputting in `shiny`, but with `nPlot()` instead. Here's my updated files:

**ui.R** (unchanged from your example except for `polycharts` -> `nvd3` in `showOutput()`)
```
require(rCharts)
shinyUI(pageWithSidebar(
  headerPanel("rCharts: Interactive Charts from R using nvd3.js"),
  
  sidebarPanel(
    selectInput(inputId = "x",
                label = "Choose X",
                choices = c('SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth'),
                selected = "SepalLength"),
    selectInput(inputId = "y",
                label = "Choose Y",
                choices = c('SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth'),
                selected = "SepalWidth")
  ),
  mainPanel(
    showOutput("myChart", "nvd3")
  )
))
```

**server.R**
```
library(rCharts)

shinyServer(function(input, output) {
  output$myChart <- renderChart({
    names(iris) = gsub("\\.", "", names(iris))
    p1 <- nPlot(input$y ~ input$x, data = iris, color = "Species", 
                group = "Species", type = 'scatterChart')
    p1$addParams(dom = 'myChart')
    return(p1)
  })
})
```

Here's what I get when running "manually":
```
names(iris) = gsub("\\.", "", names(iris))
p1 <- nPlot(SepalLength ~ SepalWidth, data = iris, color = "Species", 
            group = "Species", type = 'scatterChart')
```
![2015-03-16_214638](https://cloud.githubusercontent.com/assets/379357/6680484/f1aca930-cc25-11e4-801a-4b20c5ea40bf.png)

With `runApp()` on the above, however, I get a blank plot (even in browser mode, as I have read may make a difference with `nvd3`):
![2015-03-16_214739](https://cloud.githubusercontent.com/assets/379357/6680488/17247f62-cc26-11e4-98ce-6385f7b94307.png)

Is this something wrong with my code, or a legitimate bug? I did wonder about `nPlot()`'s ability to handle the strings from `input$x/y`. Is that an issue at all? I get, suspiciously, the same plot as my `shiny` app when I run the following:

```
p1 <- nPlot("SepalLength" ~ "SepalWidth", data = iris, color = "Species", 
            group = "Species", type = 'scatterChart')
```

This hung me up with `ggplot2` the first time I used it with `shiny`, finally figuring out that I needed to use `aes_string()` instead of the standard `aes()` since `input` would be passing strings. In fact, I was surprised that your `rPlot` example with shiny worked, as I would have expected some special treatment! Just one thought of what might be going on, but I'm quite a novice, so I really have no idea.

Many thanks for taking a look.

**Comment by ramnathv** [comment]
Don't use the formula interface here. Instead pass `x = input$x, y = input$y` to the `nPlot` function, since they are strings.

**Comment by jwhendy** [comment]
Works like a charm. Can you tell I'm coming from `ggplot` and had no idea of the other syntax? :)

As an aside, where would one look for answers like this? Is it recommended to check `lattice` documentation and everything tracks? I get nothing for `?nPlot` and only `rPlot(x, ...)` when doing `?rPlot`. There's a lot of awesome starter examples, but I have found it tricky to resolve things that begin going beyond that (and hate to pester you with a "bug" every time that occurs!).

Thanks for the quick reply -- marking closed/resolved.
