### ISSUE TITLE
nPlot addFilters not working in Shiny

### ISSUE THREAD

**Issue by Div91** [ramnathv/rCharts#611]
Hi @ramnathv,

The addFilters feature works perfectly well in R studio but fails to show me any result when called using shiny app.

Attaching a simple code here to illustrate my issue:

server.R
library(rCharts)
library(shiny)
shinyServer(
  function(input,output){
    output$plot1 <- renderChart2({
        cars <- data.frame(table(mtcars$cyl, mtcars$gear))
        colnames(cars) <- c("Cyl","Gear", "Freq")
        cars_plot <- nPlot(Freq ~ Cyl, group = 'Gear', data = cars, type = 'multiBarChart', width = 800, height=400)
        cars_plot$addFilters("Gear")          ##if I remove this line, plot gets generated.
        cars_plot
    })
})

ui.R
shinyUI(pageWithSidebar(
  headerPanel(""),
  sidebarPanel("Cars"),
  mainPanel( showOutput(("plot1"), lib = "Nvd3", package = "rCharts"))
))
  

Am I missing any particular library? Please help.

Thanks,
Divya

**Comment by ramnathv** [comment]
`addFilters` was designed to work in situations where you did not want to use Shiny. With Shiny, you are better of using UI controls provided by it.
