### ISSUE TITLE
Rcharts Gallery down

### ISSUE THREAD

**Issue by ddalal2** [ramnathv/rCharts#619]
First of all rCharts is a fantastic resource. Thank you so much for the work you've down on this.

I've noticed the rCharts Gallery http://rcharts.io/gallery/ has been down for a couple of months now. Any chance of bringing it back up or providing an alternate example gallery?

Thanks

**Comment by ramnathv** [comment]
Thanks for letting me know. I believe it is because of Google Spreadsheet API changes. I will fix it this weekend by reverting to a local copy of the csv.

**Comment by d-qn** [comment]
As a big fan of rCharts, I also noticed a few weeks ago that its chart gallery was down. As a temporary workaround you can also check the source google spreadsheet used for the gallery (only drawback: no chart thumbnail preview): 

https://docs.google.com/spreadsheets/d/1rCjzfTFG9HOqybt7OVVPNopauzZMjqmqItXQp0RPdyI/edit

**Comment by ddalal2** [comment]
Thanks! Looking forward for the gallery being back up.

**Comment by markedschroeder** [comment]
I would also like to thank you for developing rcharts, it's a really cool package.  I'm not sure if you're aware of this, but the gallery is still down.  I tried on safari, firefox, and chrome and I get a blank page.  Thanks for fixing it!

**Comment by nite** [comment]
Still down guys! Might be worth exporting your spreadsheet out of google docs & hosting it locally ;) 
XMLHttpRequest cannot load https://docs.google.com/spreadsheets/d/1rCjzfTFG9HOqybt7OVVPNopauzZMjqmqItXQp0RPdyI/pub?output=csv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rcharts.io' is therefore not allowed access.

**Comment by efh0888** [comment]
Yeah, it's still down, but thanks for posting the spreadsheet.

**Comment by nite** [comment]
Is there anything we can do to help you get the gallery back up? it would be extremely useful to promote its usage within my org

**Comment by ramnathv** [comment]
The gallery is back up. http://rcharts.io/gallery/

**Comment by nite** [comment]
Awesome, thanks for the quick response @ramnathv

**Comment by grabear** [comment]
It's down @ramnathv http://rcharts.io/gallery/

**Comment by grabear** [comment]
Discussed here:  https://github.com/rstudio/rstudio/issues/1709
And here:  https://community.rstudio.com/t/r-studio-website-broken-link-to-rcharts/2428

**Comment by ramnathv** [comment]
@grabear I forgot to renew the domain name :( I need to register an alternate domain and move things over.

**Comment by grabear** [comment]
Cheers!  Just giving you a heads up.  I was excited to check it out, but I wasn't able to view anything.
