### ISSUE TITLE
Inconsistent rPlot() results

### ISSUE THREAD

**Issue by aloboa** [ramnathv/rCharts#623]
I run the same command twice and get different plots, i.e.
x <- c(rnorm(1326/2,5,2.5),rnorm(1326/2,10,5))
y <-  rnorm(1326,15,2.5) + runif(1326,-5,5)
dftest <- data.frame(ID=1:1326,
                     x=x, y=y,
                     cl=sample(c("A","B","C"),1326,replace=TRUE))
rPlot(y ~ x, data = dftest, color = "cl", type = "point")
rPlot(y ~ x, data = dftest, color = "cl", type = "point")
have different points.
Considering
> dim(dftest)
[1] 1326   4

I think this inconsistent  behaviour is due to polycharts automatic sampling, as
mentioned in 
https://github.com/ramnathv/rCharts/issues/621

Is there any way to turn that sampling off from within rCharts commands?

Thanks

**Comment by ramnathv** [comment]
Yes. See this [issue](https://github.com/ramnathv/rCharts/issues/621) for a solution.
