### ISSUE TITLE
chart(useInteractiveGuideline = TRUE) not Working as expected

### ISSUE THREAD

**Issue by kilimba** [ramnathv/rCharts#630]
Hello,

Am trying to create a stacked area chart with an interactive guideline. However, the default tooltip seems unresponsive so I added a line to explicitly add the interactive guideline `p2$chart(useInteractiveGuideline = TRUE)`. However, on adding this line, no chart renders and using Chromes Developer Tools tells me `Uncaught TypeError: chart.useInteractiveGuideline is not a function`. Am at a loss as to what is happening. The code is as below:

```
## app.R ##
library(shiny)
library(shinydashboard)
library(rCharts)
library(curl)

consent <- read.csv(curl("https://raw.githubusercontent.com/kilimba/data/master/consent.csv"))

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    fluidRow(
      box(showOutput("distPlot2"),width = 12)
      )
    )
)

server <- function(input, output) { 
  
  output$distPlot2 <- renderChart2({
    p2 <- nPlot(HIVConsentRate ~ Year, group = 'HIVRefused', data = consent, type = 'stackedAreaChart')
    p2$chart(useInteractiveGuideline = TRUE)
    
    return(p2)
  })
}

shinyApp(ui, server)
```

Any help greatly appreciated,
Tumaini

**Comment by ramnathv** [comment]
Stacked area charts in NVD3 dont support this option.

**Comment by kilimba** [comment]
OK thanks
