### ISSUE TITLE
Highcharts xAxis label truncated with a single data point

### ISSUE THREAD

**Issue by ahewinsonDufrain** [ramnathv/rCharts#638]
When plotting a chart with a single data point, the xAxis category is truncated (in this case, "January" become "J").  This truncation is unwanted.
```
hc <- Highcharts$new()
hc$title(text = 'Active Customer vs Web Traffic')
hc$xAxis(title=list(text='Month'), categories='January')
hc$series(data=25, name='Returning', type='column',
          color='#5A1AD5', borderWidth=0)
hc
```
![screenshot 2015-07-06 13 25 57](https://cloud.githubusercontent.com/assets/8722265/8522127/e2455022-23e2-11e5-82c9-a187f47063dc.png)

The same code but with an extra data point... the category names are correct ("January", "February").
```
hc <- Highcharts$new()
hc$title(text = 'Active Customer vs Web Traffic')
hc$xAxis(title=list(text='Month'), categories=c('January', 'February'))
hc$series(data=c(25, 27), name='Returning', type='column',
          color='#5A1AD5', borderWidth=0)
hc
```
![screenshot 2015-07-06 13 26 04](https://cloud.githubusercontent.com/assets/8722265/8522132/edcfb0ae-23e2-11e5-9780-89339f26cb44.png)

**Comment by ramnathv** [comment]
Just replace `""January` with `list("January")`. The categories variable expects an array, and when you supply a single value, it creates an array by splitting the characters.
