### ISSUE TITLE
rCharts and d3heatMap (or other) in the same shiny application creates problems:

### ISSUE THREAD

**Issue by kaseyriver11** [ramnathv/rCharts#644]
Hey!

I noticed that when I call a graph from rCharts, and a heat map from d3heatMap in the same R shiny application, the second visual fails to display properly. I understand why this is so. Only the js file from the first visual is being used in the creation of the application. Do you know if there is any work being done to correct this problem? 

Thanks!

**Comment by ramnathv** [comment]
@kaseyriver11 A new version of `rCharts` that is based on `htmlwidgets` is in the works. Once I release that, it will sort the problem you are experiencing while using multiple widgets in a page.

**Comment by kaseyriver11** [comment]
@ramnathv  you are the man. Thanks for the response. 
I figured you were already on top of this!
