### ISSUE TITLE
Tooltip for each column in data frame with hplot

### ISSUE THREAD

**Issue by levithatcher** [ramnathv/rCharts#646]
I've searched and searched, but can't find how to format a tooltip properly using hPlot for a (previously unused) column in the dataframe.

The example at this link doesn't work for me in RStudio (using rCharts_0.4.5 and R 3.2.1):
http://stackoverflow.com/questions/18086812/add-values-to-rcharts-hplot-tooltip

Below is my example. How do I surface the name column in the tooltip?

Thanks!

library(rCharts)

height <- c(60, 56, 59, 60, 70)
time <- c(46, 42, 45, 45, 50)

class <- c("A","B","A","C","B")
weight <- c(140, 130, 140, 160, 180)

name <- c("jim", "joe", "bob", "tim", "larry")

all = data.frame(height,time,class,weight,name)

h1 <- hPlot(
  x = "height",
  y = "time",
  groups = "class",
  size = "weight",
  data = all,
  type = "bubble"
)

h1

**Comment by levithatcher** [comment]
While I know this isn't stackoverflow, I'm wondering if a standard format for this functionality exists and was ever placed in a doc/example. Thanks!

**Comment by d-qn** [comment]
As far as I know, you can't currently do that with rCharts::hPlot. Variables not used by highcharts for the chart can't be used in the tooltip. There is a workaround though (using rCharts::Highcharts$new instead): https://github.com/ramnathv/rCharts/issues/289 .

**Comment by levithatcher** [comment]
Thanks so much, d-qn! Very speedy and helpful!
