### ISSUE TITLE
Cannot embed rChart in RMarkdown

### ISSUE THREAD

**Issue by sshrutika** [ramnathv/rCharts#651]
when I try the below code
r1 <- rPlot(mpg ~ wt, data = mtcars, type = 'point')
r1$print('chart1', include_assets = TRUE, cdn = TRUE)

I get this output:
## </script>

**Comment by ramnathv** [comment]
Use `r1$save` to save as iframe and then embed the iframe in the document. `rCharts` will be ported to `htmlwidgets`, after which this would become more seamless.
