### ISSUE TITLE
Feature Request: Integration of Highcharts Booster Module

### ISSUE THREAD

**Issue by TonyDIRL** [ramnathv/rCharts#662]
Hi,

As always a great package that I use heavily.

Highcharts recently introduced an experimental module to support the efficient rendering of large time series.
http://www.highcharts.com/component/content/article/2-news/175-highcharts-performance-boost

This is a really awesome feature and it would be so useful to have access to this via rCharts.

Was hoping it would be as simple as modifying "addAssets"....
```
 N<-10000;h1 <- Highcharts$new()
 h1$chart(type = "spline")
 h1$series(data = sin(seq(1,N)), dashStyle = "longdash")
 h1$series(data = cos(seq(1,N)), dashStyle = "shortdot")
 h1$legend(symbolWidth = 80)
 h1$addAssets(js = "http://rawgit.com/highslidesoftware/highcharts.com/master/js/modules/boost.src.js")
 h1$addAssets(js = "http://code.highcharts.com/modules/boost.js");h1$chart(zoomType = "x");
 h1
```
Cheers

**Comment by ramnathv** [comment]
This sounds interesting. Let me take a look at the boost module and think through what is the best way to add it.

**Comment by TonyDIRL** [comment]
That would be awesome, thank you

**Comment by pachiras** [comment]
That's a great news!
I was just searching for how to do this.

**Comment by King23** [comment]
Looking forward for the release in rcharts!

**Comment by TonyDIRL** [comment]
Hi,

Just wondering if you had a chance to look at boost?

Regards

**Comment by TonyDIRL** [comment]
FYI, the highcharter package has incorporated the boost module
http://rpubs.com/jbkunst/highcharter-boost
