### ISSUE TITLE
rCharts2

### ISSUE THREAD

**Issue by knsamati** [ramnathv/rCharts#663]
Hi!
 Many thank to Dr Ramnathv for this useful package. Where can I find rCharts2 like in this video (https://www.youtube.com/watch?v=iv_3UZlNHLc)?
Thank

**Comment by ramnathv** [comment]
`rCharts2` is still under development. I will be pushing it to github once it is ready for a beta.

**Comment by knsamati** [comment]
Ok.thank very much...
