### ISSUE TITLE
nPlot not working - displays blank white

### ISSUE THREAD

**Issue by kitjosh1050** [ramnathv/rCharts#668]
Hello,

I ran the same example as what is shown on the main page:
```r
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, type = "multiBarChart")
```

In RStudio calling n1 returns nothing, just a white page with some scroll bars.

Saving the html then opening in a browser does work however.
`n1$save('n1.html')

The rest of the plot types work in RStudio

Any idea what's going on?
I'm using R version 3.2.1 (2015-06-18) 64bit on Windows 7.
Version 0.98.1103

Josh
thanks,

**Comment by ramnathv** [comment]
This is a known issue with the RStudio Viewer in Windows and NVD3 charts. I am not aware of  a way to resolve it.
