### ISSUE TITLE
Error message using rCharts

### ISSUE THREAD

**Issue by hhsieh** [ramnathv/rCharts#679]
Hi,

Thank you for creating such a great tool 'rCharts'. I am eager to learn and embed an interactive graph in my Shiny APP. However, a I tried to run some code on rChart tutorial page, the following error occurred.

Error in FUN(left, right) : 
  comparison (3) is possible only for atomic and list types
Called from: .rs.breakOnError(TRUE)
Browse[1]> 

Could you help me identify what the problem is? I have closed RStuiod, reopened and reinstalled the package, but the error still occurs. Thank you!!

HH

**Comment by hhsieh** [comment]
The error message that pops up in HELP is 
Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/rCharts/help/rCharts.rdb' is corrupt

**Comment by ramnathv** [comment]
I would recommend closing out your R session and restarting again. This error occurs when you are trying to update a package that is already loaded, which could be one of the dependencies of `rCharts`.

**Comment by hhsieh** [comment]
Thanks, ramnathv. I closed my R session and restarted, but it did not help. I still obtain the same error message. Is there any other possibility? I am not very familiar this. Thank you for your help!!

**Comment by hhsieh** [comment]
Well, after I cleaned all of my data in R, rCharts runs!!! I think I have no problem now. Thank you very much for your help!!

**Comment by ramnathv** [comment]
Great.
