### ISSUE TITLE
Cannot install rCharts

### ISSUE THREAD

**Issue by gdickens** [ramnathv/rCharts#685]
Hello, 

I've gone through the previous issues raised about this problem and have not come to a solution as to how to successfully install rCharts which I currently need to participate in a team project.  

Have installed devtools, and rTools. Have tried to install it both using 32 and 64 bit R.  

Have tried to install rCharts through downloading the package via "https://github.com/ramnathv/rCharts/archive/master.zip" and manually installing (both via RStudio and Rbase). 

and

Have tried installing through the standard command 

> "require(devtools)
> install_github('ramnathv/rCharts')" 

Have changed the installation directory to a root directory (C:) and have changed the temporary files folder to c:/Temp. Both of these are in response to similar errors people have experienced, but neither solved the problem.  

I recently installed the identical versions of R and RStudio on a server and was able to install rCharts, so I tried to do a fresh install of R, but this didn't solve the problem either. 

**When trying to run via R 3.1.3 or R 3.2.3 I get something like:**
_Installing rCharts
"C:/R/R-31~1.3/bin/i386/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Temp/RtmpAfahkK/devtoolscb85d1b738a/ramnathv-rCharts-389e214"  \
  --library="C:/Users/.../R/win-library/3.1" --install-tests 

Error: Command failed (65535)_

**When trying to install locally via zip/tar I get**: 

either no response (and rCharts isn't installed) OR: 
Warning in install.packages :
  installation of package ‘C:/.../rCharts.tar.gz’ had non-zero exit status

**OS: Windows 10** 
**R Studio Version 0.99.491**
**R version 3.2.3**

Any help would be greatly appreciated, thank you in advance :)

**Comment by gdickens** [comment]
I've spent more time trying to figure out the problem via changing environment variables, uninstalling/reinstalling and ensuring dependencies are installed. No luck.

Would be really grateful for suggestions. I'm quite new to R, but had hoped I'd been able to troubleshoot this one myself. Alas, I can't.

**Comment by gdickens** [comment]
so I'm taking that nobody has any ideas here? Any help/suggestions would be greatly appreciated.

**Comment by rudeska** [comment]
same problem, I can't install the library in windows7

**Comment by gdickens** [comment]
Thanks for the suggestion rudeska. I tried that and received the 'non-zero exit status' error again :/ 

I actually suspect the errors are to do with Windows, but I haven't been able to solve the issue so I guess I'll have to use a different package for the project.

**Comment by romunov** [comment]
Are you able to install other packages from GitHub? Or perhaps build one locally?

**Comment by gdickens** [comment]
Sorry for the delay. I wasn't sure how to build a package locally (unless you mean downloading the .tar file and installing it that way?) but I did try and install ggplot using the same command and received an identical error. 

ie when loading devtools and using the command "install_github("hadley/ggplot2")"

I also get "--no-site-file  \
  --no-environ --no-save --no-restore CMD  \
  INSTALL  \" 

and an error "Error: Command failed (65535)"

Which I'm assuming is pointing to an issue my setup has outside of rCharts.

**Comment by romunov** [comment]
It would be a safe bet that your tool chain is messed up and may not be exclusively rCharts related.

**Comment by gdickens** [comment]
Seems like a reasonable conclusion and one that I had considered, but from memory when testing the install of another github package it worked (although gggplot didn't when I tried above so it seems more likely). 

Any tips to troubleshoot it? 

I've done a lot of googling under the assumption that it's a generic windows error as hadley noted this for one of his packages, but the only time I've seen the problem being resolved was when there were changes made to the package in question by the author via github (hence why I posted this issue here as it seemed that it might have been an rCharts problem). 

I've tried installing rtools, uninstalling and reinstalling R etc etc. I had suspected it had something to do with my environment variables in Windows, but attempts to fix it via this route didn't result in a solution.

**Comment by ramnathv** [comment]
This is a Windows error. See here for some suggestions on how to fix it http://www.wiki-errors.com/err.php?wiki=65535. It as to do with your OS settings.

**Comment by romunov** [comment]
Check paths and that you are able to access tools in the toolchain. Perhaps
document what is going on and ask on stackoverflow.

**Comment by gdickens** [comment]
Thanks Ramnathv. I did see that fix, however, the tool they provide is malware so I didn't think it was likely to be a legitimate solution. Thank you very much for the suggestion though and for your time creating this package, I've got it to work on my Ubuntu server with great results. 

Romunov, let me do the research and see if I can troubleshoot it that way. If I find a solution that works I'll post it up here as I've seen this issue come up before. I might just test out the system restore solution first as I'm feeling a bit lazy.

**Comment by gdickens** [comment]
Okay, after lots of research and trial and error I managed to get it to work. I'm not sure which solution worked but below is a list of the most recent steps I went through to get it to work. 

From what I can tell before rCharts worked and I called "devtools::has_devel()" in R it originally only returned an error 

> "-no-site-file --no-environ --no-save --no-restore --quiet  \
>   CMD SHLIB foo.c "
> 

However, after following the steps below it returns the same error, but then returns 'TRUE': 

> "gcc -m64 -I"C:/PROGRA~1/R/R-32~1.4/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c foo.c -o foo.o
> gcc -m64 -shared -s -static-libgcc -o foo.dll tmp.def foo.o -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.4/bin/x64 -lR"


- Told Rstudio to 'Save all files prior to building packages" (via the Packages section of the Options menu)
- Uninstalled my python installations (to ensure they weren't altering the environmental path variables)
- Reinstalled Rtools3.3.exe (I'd tried this before so not sure if this is what worked)
- Changed my cran mirror from the default (I read this helped with a similar issue). 
- Installed devtools from github Using the command: "devtools::install_github("hadley/devtools")"
- Installed the InnoSetup installer (which is a package that works alongside Rtools) 

I was actually trying each step one by one so that I could identify exactly what the problem was, but then I became annoyed with nothing working and decided to just try everything. 

Rstudio Version 0.99.891
R version 3.2.4
Windows 10

**Comment by gdickens** [comment]
Interestingly I was also having problems installing QGIS installing. QGIS now works which I'm assuming is a result of uninstalling the different Python platforms (as it I understand it uses Python).

**Comment by rawkintrevo** [comment]
Regarding this being a windows problem:  I am using Ubuntu 14.04 and getting the same error, at the CLI.

**Comment by shivamsarin1** [comment]
Hi All,,
I tried all the methods told above nothing seems to be working for me.

1) install_github("ramnathv/rCharts")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't resolve host name

2)install.packages("rCharts.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/shivam_Sarin/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
- installing _source_ package 'rCharts' ...
  *\* R
  *\* demo
  *\* inst
  *\* preparing package for lazy loading
  Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
  ERROR: lazy loading failed for package 'rCharts'
- removing 'C:/Users/shivam_Sarin/Documents/R/win-library/3.3/rCharts'
  Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-3.3.1/bin/x64/R" CMD INSTALL -l "C:\Users\shivam_Sarin\Documents\R\win-library\3.3" "rCharts.tar.gz"' had status 1
  Warning in install.packages :
  installation of package ‘rCharts.tar.gz’ had non-zero exit status

Please help.
Windows 10 x64

**Comment by ramnathv** [comment]
The error message points to your not having `Rcpp` installed.

**Comment by shivamsarin1** [comment]
Thanks Ramnathv. Finally installed it.

**Comment by indicolite** [comment]
> install_github('ramnathv/rCharts')
Installation failed: Timeout was reached: Resolving timed out after 10000 milliseconds
> install_github('ramnathv/rCharts')
Installation failed: Timeout was reached: Resolving timed out after 10264 milliseconds
> install_github('ramnathv/rCharts')
Downloading GitHub repo ramnathv/rCharts@master
from URL https://api.github.com/repos/ramnathv/rCharts/zipball/master

Thanks Ramnathv!!
