### ISSUE TITLE
Max Points for Leaflet / rMaps

### ISSUE THREAD

**Issue by GtheSheep** [ramnathv/rCharts#688]
Hi,

Is there a max points limit for Leaflet or anything in rMaps? I'm trying to plot ~2000 data points but they don't all seem to render, wondering if it's 400 like some others? Is there a way around this?

Thanks

**Comment by ramnathv** [comment]
I don't think there should be a limit to the number of points you can plot with `leaflet`. I would recommend taking a look at the rstudio/leaflet package which is a more comprehensive and well maintained implementation of leaflet.
