### ISSUE TITLE
Could not find function "install_github"

### ISSUE THREAD

**Issue by ktdesignbox** [ramnathv/rCharts#718]
I am new in R Studio. I tried to download the libraries, but this message showed up:

> require(devtools)
> Loading required package: devtools
> Warning message:
> In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called 租evtools・> install_github('ramnathv/rCharts')
> Error: could not find function "install_github"

**Comment by ramnathv** [comment]
For some reason, `devtools` is not correctly installed on your machine. Can you run `install.packages("devtools")` and try the installation again?

**Comment by ktdesignbox** [comment]
- installing _source_ package 'rCharts' ...
  *\* R
  *\* demo
  *\* inst
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* testing if installed package can be loaded
  **\* arch - i386
  **\* arch - x64
- DONE (rCharts)

Looks like it was ok this time. Thank you!

**Comment by ramnathv** [comment]
You are welcome.
