### ISSUE TITLE
Problem installing rCharts

### ISSUE THREAD

**Issue by eaganan** [ramnathv/rCharts#89]
Hi,

I 'm trying to install rChart using the comands bellow but i have had problems. I looking for on google a SO but I didn't find a solution.

Here is my configuration sesion and the kind of error.

I apreciate for your help

R version 3.0.0 (2013-04-03) -- "Masked Marvel"
Copyright (C) 2013 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

> require(devtools)
> Loading required package: devtools
> Mensajes de aviso perdidos
> package ‘devtools’ was built under R version 3.0.1 
> find_rtools()
> [1] TRUE
> dev_mode(on=T)
> Dev mode: ON
> d> install_github("rCharts", "ramnathv")
> Installing github repo(s) rCharts/master from ramnathv
> Installing rCharts.zip from https://github.com/ramnathv/rCharts/archive/master.zip
> Installing rCharts
> "C:/PROGRA~1/R/R-30~1.0/bin/x64/R" --vanilla CMD INSTALL "C:\Users\Edward  \
>   Gañan\AppData\Local\Temp\RtmpSWcI7y\rCharts-master"  \
>   --library="C:/Users/Edward Gañan/Documents/R-dev" --with-keep.source 

Warning: invalid package 'C:\Users\Edward Gañan\AppData\Local\Temp\RtmpSWcI7y\rCharts-master'
Error: ERROR: no packages specified
Error: Command failed (1)

**Comment by Guiui21** [comment]
Hi,

I'm trying to download ShinyDash on my shiny server on CentOS. My problem is that with shiny server I have to install the package with root privilege so I have to do it through the terminal. I'm using devtools and install_github to do so. When I do that, I get this error: 

Error in contrib.url(repos, type) :
trying to use CRAN without setting a mirror 

What should I do ? 

Thanks.

**Comment by dnchari** [comment]
You should use 

sudo /usr/bin/R -e "devtools::install_github('ramnathv/rCharts')"
